#############################################################################
# Configuration information for the rodent windows project
#############################################################################

winsize_kb: "10kb"
# Window size string

window_file: "/n/holylfs05/LABS/informatics/Users/gthomas/mus-t-haplotype/mus-t-windows/data/mm10-10kb-window-stats.tsv"
# The window stats file (from 16_get_window_stats.py)

expected_seqs: 6
# The "Presence" filter: all 6 species should be in the filtered alignment

min_uniq_seqs: 4
# The minimum number of unique sequences required to be in the alignment (for IQtree)

max_missing_seqs: 0
# The maximum number of sequences that are all gap or missing (for IQtree)

aln_base_dir: "/n/holylfs05/LABS/informatics/Users/gthomas/mus-t-haplotype/mus-t-windows/03-fasta-no-anc-filter/"
# Output directory from 16_get_window_stats.py

tree_out_dir: "/n/holylfs05/LABS/informatics/Users/gthomas/mus-t-haplotype/mus-t-windows/04-iqtree/"
# Desired output directory, will have subdirs for gene trees (loci), astral tree, and concat tree

chromes: ["chr17"]
# The chromosome to run (only 17 available for this project)

outgroup: "pahari"
# Outgroup to root trees by

#############################################################################

